---
- name: install snap
  package:
    name: snapd
  become: true
- name: install microk8s
  snap:
    name: microk8s
    classic: true
  become: true

- name: add `{{ k8s_admin }}` user to `microk8s` group
  user:
    name: "{{ k8s_admin }}"
    append: true
    groups: microk8s
  become: true
- name: reset connection for group reflection
  meta: reset_connection

- name: wait microk8s status
  command:
    cmd: /snap/bin/microk8s status --wait-ready
- name: turn on dashboard addon
  shell: |
    /snap/bin/microk8s enable dns dashboard
